const gridlinkCities = [
    {
	title: "Eastern Cape",
	cities: [
	    "East London",
	    "Port Elizabeth",
	    "Uitenhage",
	    "Mthatha",
	    "Grahamstown",
	    "Queenstown",
	    "Aliwal North",
	    "Cradock",
	    "Port Alfred",
	    "Bhisho",
	    "Butterworth",
	    "Kirkwood",
	    "Fort Beaufort",
	    "Cofimvaba",
	    "Lady Frere",
	    "Sterkspruit",
	    "Middelburg",
	    "Graaff-Reinet",
	    "Humansdorp",
	    "Matatiele",
	    "Stutterheim",
	    "Dutywa",
	    "Kei Mouth",
	    "Mazeppa Bay",
	    "Qolora Mouth"
	],
    },
    {
	title: "Free State",
	cities: [
	    "Bloemfontein",
	    "Welkom",
	    "Botshabelo",
	    "Virginia",
	    "Kroonstad",
	    "Sasolburg",
	    "Parys",
	    "Phuthaditjhaba",
	    "Bethlehem",
	    "Ficksburg",
	    "Harrismith",
	    "Ladybrand",
	    "Vrede",
	    "Bothaville",
	    "Wesselsbron",
	    "Frankfort",
	    "Winburg",
	    "Tweeling",
	    "Kestell",
	    "Hennenman",
	    "Odendaalsrus",
	    "Heilbron",
	    "Ventersburg",
	    "Thaba Nchu",
	    "Virginia"
	],
    },
    {
	title: "Gauteng",
	cities: [
	    "Johannesburg",
	    "Pretoria",
	    "Soweto",
	    "Krugersdorp",
	    "Vereeniging",
	    "Boksburg",
	    "Randfontein",
	    "Benoni",
	    "Germiston",
	    "Springs",
	    "Roodepoort",
	    "Alberton",
	    "Midrand",
	    "Kempton Park",
	    "Centurion",
	    "Edenvale",
	    "Brakpan",
	    "Nigel",
	    "Cullinan",
	    "Akasia",
	    "Soshanguve",
	    "Sandton",
	    "Randburg",
	    "Vanderbijlpark",
	    "Evaton",
	    "Heidelberg",
	    "Meyerton",
	    "Carletonville",
	    "Westonaria",
	    "Mabopane",
	    "Bronkhorstspruit",
	    "Rayton",
	    "Irene",
	    "Walkerville",
	    "Sedibeng",
	    "Ekurhuleni",
	    "Tshwane",
	    "City of Johannesburg Metropolitan Municipality"
	],
    },
    {
	title: "KwaZulu-Natal",
	cities: [
	    "Durban",
	    "Pietermaritzburg",
	    "Newcastle",
	    "Ladysmith",
	    "Richards Bay",
	    "Kokstad",
	    "Utrecht",
	    "Scottburgh",
	    "Eshowe",
	    "Howick",
	    "Hillcrest",
	    "Port Shepstone",
	    "Estcourt",
	    "Mooi River",
	    "Empangeni",
	    "Stanger",
	    "Hluhluwe",
	    "Mkuze",
	    "Pongola",
	    "Vryheid",
	    "Dundee",
	    "Greytown",
	    "Bulwer",
	    "Merrivale",
	    "Ixopo",
	    "Umzimkhulu",
	    "Kokstad",
	    "Ballito",
	    "Gingindlovu",
	    "Uvongo",
	    "Margate",
	    "Harding",
	    "Port Edward",
	    "Glenwood",
	    "Musgrave",
	    "Westville",
	    "Morningside",
	    "Umhlanga",
	    "Verulam",
	    "Tongaat",
	    "Chatsworth",
	    "Phoenix",
	    "Pinetown",
	    "Hibberdene",
	    "Elandslaagte",
	    "Gingindlovu",
	    "Impendle",
	    "Bergville",
	    "Balgowan",
	    "Nottingham Road",
	    "Wartburg",
	    "Albert Falls",
	    "Hilton",
	    "Underberg",
	    "Richmond",
	    "Ashburton",
	    "Hammarsdale",
	    "Camperdown",
	    "Umzinto",
	    "Umzumbe",
	    "Himeville",
	    "Kranskop",
	    "Maphumulo",
	    "Mandeni",
	    "Msinga",
	    "Ndwedwe",
	    "Pomeroy",
	    "Sundumbili",
	    "Ubombo",
	    "Weenen",
	    "Dargle",
	    "Rosetta",
	    "Fort Nottingham",
	    "Greylingstad",
	    "Inchanga",
	    "Lidgetton",
	    "Mount Currie",
	    "Mooiriver",
	    "Nkandla",
	    "Noodsberg",
	    "Ixopo",
	    "Creighton",
	    "New Hanover",
	    "Baynesfield",
	    "Mhlabatshane",
	    "Nqutu",
	    "Nyoni",
	    "Babanango",
	    "Colenso",
	    "Elandskraal",
	    "Kranskop",
	    "Mount Edgecombe",
	    "Muden",
	    "Nkwalini",
	    "Umkomaas",
	    "Amanzimtoti",
	    "Umdloti",
	    "Isipingo",
	    "Umzinto",
	    "Mandini",
	    "KwaDukuza",
	    "Tugela Ferry",
	    "Manguzi",
	    "Kosi Bay",
	    "Mbazwana",
	    "Mkuze",
	    "KwaMbonambi",
	    "Mtubatuba",
	    "St Lucia",
	    "Ubombo",
	    "Ingwavuma",
	    "Jozini",
	    "Nongoma",
	    "Paulpietersburg",
	    "Mseleni",
	    "Ntambanana",
	    "Nkonyeni",
	    "Empangeni",
	    "Richards Bay",
	    "Pietermaritzburg",
	    "Durban",
	    "Richards Bay",
	    "Empangeni",
	    "Ladysmith",
	    "Newcastle",
	    "Utrecht",
	    "Vryheid",
	    "Estcourt",
	    "Greytown",
	    "Hilton",
	    "Howick",
	    "Kokstad",
	    "Margate",
	    "Scottsburgh",
	    "Umzinto",
	    "Umzumbe",
	    "Bergville",
	    "Elandslaagte",
	    "Harding",
	    "Ixopo",
	    "Mooi River",
	    "Mount Edgecombe",
	    "Port Shepstone",
	    "Richmond",
	    "Tongaat",
	    "Umdloti",
	    "Umhlanga Rocks",
	    "Amanzimtoti",
	    "Ballito",
	    "Chatsworth",
	    "Hillcrest",
	    "Isipingo",
	    "Kloof",
	    "Phoenix",
	    "Westville",
	    "Bluff",
	    "Gillitts",
	    "Pinetown",
	    "Queensburgh",
	    "Waterfall",
	    "Welkom"
	],
    },
    {
	title: "limpopo",
	cities: [
	    "Polokwane",
	    "Belabela",
	    "Giyani",
	    "Lebowakgomo",
	    "Louis Trichardt",
	    "Lulekani",
	    "Lephalale",
	    "Mankweng",
	    "Modimolle",
	    "Mokopane",
	    "Musina",
	    "Nkowankowa",
	    "Phalaborwa",
	    "Tzaneen",
	    "Thohoyandou",
	    "Vivo"
	],
    },
    {
	title: "Mpumalanga",
	cities: [
	    "Barberton",
	    "Belfast",
	    "Carolina",
	    "Delmas",
	    "Dullstroom",
	    "Ermelo",
	    "Graskop",
	    "Groblersdal",
	    "Hazyview",
	    "Komatipoort",
	    "Lydenburg",
	    "Machadodorp",
	    "Malelane",
	    "Middelburg",
	    "Nelspruit",
	    "Piet Retief",
	    "Sabie",
	    "Secunda",
	    "Standerton",
	    "Volksrust",
	    "Wakkerstroom",
	    "White River"
	],
    },
    {
	title: "North West",
	cities: [
	    "Brits",
	    "Fochville",
	    "Hartbeespoort",
	    "Klerksdorp",
	    "Koster",
	    "Lichtenburg",
	    "Mafikeng",
	    "Magaliesburg",
	    "Mahikeng",
	    "Potchefstroom",
	    "Rustenburg",
	    "Schweizer-Reneke",
	    "Stilfontein",
	    "Ventersdorp",
	    "Vryburg",
	    "Wolmaransstad",
	    "Zeerust"
	],
    },
    {
	title: "Northern Cape",
	cities: [
	    "Kimberley",
	    "Upington",
	    "De Aar",
	    "Springbok",
	    "Kathu",
	    "Carnarvon",
	    "Postmasburg",
	    "Calvinia",
	    "Hartswater",
	    "Prieska",
	    "Kuruman",
	    "Alexander Bay",
	    "Victoria West",
	    "Groblershoop",
	    "Port Nolloth",
	    "Daniëlskuil",
	    "Hondeklipbaai",
	    "Sutherland",
	    "Augrabies",
	    "Keimoes",
	    "Griekwastad",
	    "Orania",
	    "Kanoneiland",
	    "Riemvasmaak",
	    "Loeriesfontein",
	    "Pofadder",
	    "Olifantshoek",
	    "Askham",
	    "Brandvlei",
	    "Van Wyksvlei",
	    "Kakamas",
	    "Noupoort",
	    "Mier",
	    "Marydale",
	    "Vanderkloof",
	    "Kathu SP",
	    "Kakamas SP",
	    "Keimoes SP",
	    "Prieska SP",
	    "Van Zylsrus"
	],
    },
    {
	title: "Western Cape",
	cities: [
	    "Cape Town",
	    "Stellenbosch",
	    "George",
	    "Paarl",
	    "Worcester",
	    "Knysna",
	    "Mossel Bay",
	    "Oudtshoorn",
	    "Hermanus",
	    "Saldanha",
	    "Swellendam",
	    "Vredenburg",
	    "Ceres",
	    "Beaufort West",
	    "Robertson",
	    "Witbank",
	    "Atlantis",
	    "Malmesbury",
	    "Langebaan",
	    "Montagu",
	    "Caledon",
	    "Calitzdorp",
	    "Cape Agulhas NU",
	    "Cape Town",
	    "Cape Town SP",
	    "Ceres",
	    "Citrusdal",
	    "Clanwilliam SP",
	    "Darling",
	    "De Doorns",
	    "De Kelders",
	    "Doringbaai",
	    "Durbanville SP",
	    "Eendekuil",
	    "Elands Bay",
	    "Franschhoek",
	    "Franskraal",
	    "George",
	    "Gouda",
	    "Graaff-Reinet",
	    "Gouritsmond",
	    "Greyton",
	    "Grotto Bay",
	    "Heidelberg WC",
	    "Herolds Bay",
	    "Hopefield",
	    "Houw Hoek",
	    "Jacobsbaai",
	    "Klapmuts",
	    "Knysna",
	    "Klawer",
	    "Kommetjie",
	    "L'Agulhas",
	    "Ladismith",
	    "Lamberts Bay",
	    "Langebaan",
	    "Langebaanweg",
	    "Lutzville",
	    "Laingsburg",
	    "Malmesbury",
	    "Malgas",
	    "Matjiesfontein",
	    "McGregor",
	    "Melkbosstrand",
	    "Montagu",
	    "Mossel Bay",
	    "Oudtshoorn",
	    "Paarl",
	    "Paternoster",
	    "Pearly Beach",
	    "Pearly Beach SP",
	    "Piket-bo-berg",
	    "Piketberg",
	    "Piketberg NU",
	    "Plettenberg Bay",
	    "Porterville",
	    "Porterville SP",
	    "Prince Albert",
	    "Prince Alfred Hamlet",
	    "Riebeek West",
	    "Riebeek-Kasteel",
	    "Riversdale",
	    "Rooi Els",
	    "Saldanha",
	    "Saldanha Bay SP",
	    "Saron",
	    "Saron SP",
	    "Sedgefield",
	    "Simon's Town",
	    "Stellenbosch",
	    "Stanford",
	    "Stilbaai SP",
	    "Strand",
	    "Strandfontein",
	    "Struisbaai",
	    "Suurbraak",
	    "Swartland NU",
	    "Swellendam",
	    "Swellendam NU",
	    "Swellendam Rural",
	    "Tulbagh",
	    "Vanrhynsdorp"
	]
    }
]
